### ISSUE TITLE
Different "look" in dev and production mode

### ISSUE THREAD

**Issue by Lazarus535** [jquintozamora/react-typescript-webpack2-cssModules-postCSS#103]
The problem:

The demo page does not look the same in dev mode and in production mode.
The CSS stuff seems all missing in the production setting.
The content of the `main.css` in `build/` seem to be javascript not CSS.

How to reproduce:
`git clone repo`
`cd repo`
`npm install`
`npm run build`
#open index.html with browser of choice
`npm run start`
#go to localhost:3000

Notice the difference in appearance of the two sites.

I suspect that webpack is not packing the CSS correctly, but i lack the insight to fix it myself. :-(

**Comment by jquintozamora** [comment]
Hi @Lazarus535 ,
Thanks for reporting this.
I've updated webpack configuration for extract css plugin. Now it should works fine.

https://github.com/jquintozamora/react-typescript-webpack2-cssModules-postCSS/commit/e1a219399fc90e81949db355b8d1c35e685ebe9f
