### ISSUE TITLE
Problem with VSC auto-formatting on save conflicting with project lint rules

### ISSUE THREAD

**Issue by kristianmandrup** [jquintozamora/react-typescript-webpack2-cssModules-postCSS#157]
Is this related to TSLint or would it typically be some other plugin interfering?

Specifically, in my environment it enforces a space before the `:` in a variable type declaration which conflicts with the linting rules specified in this project.

I also have *Prettier* plugin installed and active

Prettier's Settings

Settings will be read from (listed by priority):

Prettier configuration file
`.editorconfig`

You can turn on format-on-save on a per-language basis by scoping the setting:

```
// Set the default
"editor.formatOnSave": false,
// Enable per-language
"[javascript]": {
    "editor.formatOnSave": true
}
```

TSLint config to enforce correct rule (no space before `:`)

https://github.com/palantir/tslint

```js
    "typedef-whitespace": [
      true,
      {
        "call-signature": "nospace",
        "index-signature": "nospace",
        "parameter": "nospace",
        "property-declaration": "nospace",
        "variable-declaration": "nospace"
      },
      {
        "call-signature": "onespace",
        "index-signature": "onespace",
        "parameter": "onespace",
        "property-declaration": "onespace",
        "variable-declaration": "onespace"
      }
    ],
```

Any suggestions?

**Comment by kristianmandrup** [comment]
Trying the following in `.editorconfig`

```js
[*.ts]
prettier.tslintIntegration = true
```

Hoping that Prettier will then pick up my tslint configuration and use it.

**Comment by kristianmandrup** [comment]
Doesn't seem to work. Looks like the solution could be here:
https://alexjoverm.github.io/2017/06/12/Use-Prettier-with-TSLint-and-be-happy/

And https://www.npmjs.com/package/tslint-config-prettier

Get started:

`npm install -D tslint-config-prettier`

Make sure you've already set up tslint and prettier.

Then, extend your `tslint.json`, and make sure `tslint-config-prettier` is at the end:

```js
{
  "extends": [
    "tslint:latest",
    "tslint-config-prettier"
  ]
}
```

There is even an egghead tutorial: https://egghead.io/lessons/typescript-use-prettier-with-tslint-without-conflicts-08410c3d

**Comment by kristianmandrup** [comment]
Still not working. Driving me nuts. Finding a needle in a haystack. Modern development is a jungle!

I can verify that my VSC user settings are set to: 

```
"editor.formatOnSave": true,
```

Setting to false disables all formatting on save as expected. Now, what is controlling this shit and overriding my lint/prettier settings!?

**Comment by kristianmandrup** [comment]
WTF!?

https://alexjoverm.github.io/2017/06/12/Use-Prettier-with-TSLint-and-be-happy/#The-solution

The solution
It’s very simple:

Let Prettier take care of code formatting, and TSLint of the rest

That’s why I’ve created tslint-config-prettier. It disables all TSLint formatting related rules, as well as for tslint-react and tslint-eslint-rules.

So what IS the solution here? Now my TSLint rule is disabled. Then I need to set a Prettier rule instead? is there such a rule? anyone?

I still get TSlint complaining after each save:

```
[tslint] expected nospace before colon in parameter (typedef-whitespace)
```

This is my `tslint.json` file. Note the `typedef-whitespace` rule I've introduced. Still not working!

```json
{
  "extends": [
    "tslint:latest",
    "tslint-react",
    "tslint-config-prettier"
  ],
  "rules": {
    "typedef-whitespace": [
      true,
      {
        "call-signature": "nospace",
        "index-signature": "nospace",
        "parameter": "nospace",
        "property-declaration": "nospace",
        "variable-declaration": "nospace"
      },
      {
        "call-signature": "onespace",
        "index-signature": "onespace",
        "parameter": "onespace",
        "property-declaration": "onespace",
        "variable-declaration": "onespace"
      }
    ],
    "ban": [
      true, [
        "Object",
        "assign",
        "use TS2.1 object spread { ...a, ...b }"
      ],
      [
        "describe",
        "only"
      ],
      [
        "it",
        "only"
      ]
    ],
    "linebreak-style": [
      true,
      "LF"
    ],
    "no-invalid-this": [
      true,
      "check-function-in-method"
    ],
    "variable-name": [
      "ban-keywords",
      "check-format",
      "allow-leading-underscore",
      "allow-pascal-case"
    ],
    "trailing-comma": [
      false
    ],
    "no-console": false,
    "no-shadowed-variable": false,
    "max-line-length": [
      180
    ],
    "max-classes-per-file": [
      true,
      5
    ],
    "object-literal-sort-keys": false,
    "jsx-no-multiline-js": false,
    "ordered-imports": [
      false
    ],
    "semicolon": [
      true,
      "never"
    ],
    "quotemark": [
      true,
      "single"
    ]
  },
  "jsRules": {
    "object-literal-shorthand": true,
    "trailing-comma": [
      false
    ]
  }
}
```

**Comment by jquintozamora** [comment]
Hi @kristianmandrup ,

Thanks for your feedback.

> So what IS the solution here? Now my TSLint rule is disabled. Then I need to set a Prettier rule instead? is there such a rule? anyone?
> You can still work with the combination of Prettier / TSLint.
> There is no Prettier rules like TSLint, but you can still configure some rules: https://prettier.io/docs/en/configuration.html
> "tslint-config-prettier" is going to help on disabling from prettier / tsling these rules which are in concflict. 
> I have update the boilerplate with ".prettierrc" file with basic config, add "tslint-config-prettier, add "prettier VS extension" on recommended extensions.
> `{
  "extends": ["tslint:latest", "tslint-react", "tslint-config-prettier"],
  "rules": {
    "ban": [
      true,
      ["Object", "assign", "use TS2.1 object spread { ...a, ...b }"],
      ["describe", "only"],
      ["it", "only"]
    ],
    "object-literal-sort-keys": false,
    "variable-name": [
      "ban-keywords",
      "check-format",
      "allow-leading-underscore",
      "allow-pascal-case"
    ],
    "max-line-length": [180],
    "max-classes-per-file": [true, 5]
  },
  "jsRules": {
    "object-literal-shorthand": true
  }
}`

Now, in my opinion, could be good to use Prettier as formatting tool and TSLint as a linter on my development pipeline. 

> Note: I, personally, don't like to use prettier on my development pipeline on an automatic way, because I preffer to format documents manually and then use Linting as checker not as formatting tool, but this is a personal decision.

Hope that Helps!

**Comment by kristianmandrup** [comment]
Thanks for responding so quickly. I found a solution that works directly with TSLint using the built in `--fix` option

Documented solutions in my own fork in [Troubleshoot](https://github.com/tecla5/react-typescript-webpack2-cssModules-postCSS/blob/master/Troubleshoot.md) document

Sett the following VSC preferences via the top menu in VSC: `Code - Preferences - Settings - User settings`:

Add `"tslint.autoFixOnSave": true,`

```
  "editor.formatOnSave": true,
  "tslint.autoFixOnSave": true,
```

Works like a charm :)
