### ISSUE TITLE
Unable to produce stats

### ISSUE THREAD

**Issue by ElanHasson** [jquintozamora/react-typescript-webpack2-cssModules-postCSS#3]
npm run stats fails:

This is in an unmodified clone, after npm install.

![image](https://user-images.githubusercontent.com/234704/29583804-a53ce7b2-874f-11e7-8268-a42ccd4bfc92.png)

**Comment by jquintozamora** [comment]
Thanks @ElanHasson , 
Solved now, including new scripts line at package.json.
