### ISSUE TITLE
npm run build does not include content from public in build

### ISSUE THREAD

**Issue by ElanHasson** [jquintozamora/react-typescript-webpack2-cssModules-postCSS#4]
I may be looking in the wrong place, but the npm run build doesn't produce all that is needed to deploy the app in the build folder.

Should I be copying and overwritting build/* over public/ to deploy?

My end goal is to have a single folder to use as a web root for static content.

**Comment by jquintozamora** [comment]
Thanks @ElanHasson , 

I've included copy-webpack-plugin to copy all the content from public to build folder except index.html file which is provided by html-webpack-plugin with css and js links injected.

Let me know if any issue.

**Comment by ElanHasson** [comment]
I'm unable to start it... prod build seems to work though

I did an npm install to add dependency but dev fails

![image](https://user-images.githubusercontent.com/234704/29615142-c1f03c34-87da-11e7-86ee-a899d3088f91.png)

**Comment by jquintozamora** [comment]
Hi @ElanHasson , 

I think that's because you have other app running on port localhost:3000.

Could you check it?

**Comment by ElanHasson** [comment]
That's exactly what it was. Thanks!

Any chance you could share your launch/tasks.json?

**Comment by jquintozamora** [comment]
I'm not using tasks.json on that template ... Using cmd window directly.
