### ISSUE TITLE
typings-for-css-modules-loader is gone? 

### ISSUE THREAD

**Issue by s-KaiNet** [jquintozamora/react-typescript-webpack2-cssModules-postCSS#531]
Hi Jose!   
I noticed that the latest version doesn't have `typings-for-css-modules-loader` in webpack configs.   

When I tried to add `.another` property in `Viewer.module.css` and reference it in `Viewer.tsx` via `className={styles.another}`, I received a TS error   
> Property 'another' does not exist on type 'typeof import("C:/Projects/gh/frk/react-typescript-webpack2-cssModules-postCSS/app/src/components/Viewer/Viewer.module.css")'.  

While webpack build works, there are errors in VSCode and in console output. Is it works as intended or am I doing something wrong?

**Comment by jquintozamora** [comment]
Hello Sergei,
Unfortunately `typings-for-css-modules-loader` is not working with recent version of webpack + plugins. So, I decided to remove it on benefit to adding new versions. 

Please let me know if you find better way to create typings automatically for css props. Also, alternatively you can add you new prop `.another` to .css.d.ts file manually.

Cheers!

**Comment by s-KaiNet** [comment]
I ended up with [css-modules-typescript-loader](https://github.com/seek-oss/css-modules-typescript-loader) which works pretty good without lots of modifications.   

I added the PR so you can take a look and merge if it's OK for you.

**Comment by s-KaiNet** [comment]
BTW I had to skip lint with --no-verify because for some reason `lint-staged` ignores `--exclude` param for tslint and tries to lint `*.d.ts` files as well.

**Comment by jquintozamora** [comment]
Approved you PR, thanks!

About lint-staged, I have pending task to upgrade `lint-staged` to latest version, maybe that solve the issue.

**Comment by s-KaiNet** [comment]
Cool, thank you!
